export {
  DEEPER_EXPLANATION_PROMPT,
  ELI5_PROMPT,
  FLASHCARD_PROMPT,
  parseGeminiResponse,
  QUIZ_PROMPT,
  STUDY_PLAN_PROMPT,
  SUMMARY_PROMPT,
  TRUE_FALSE_PROMPT,
} from '../../lib/prompts.js';
